version: "3.8"
services:
  build-test:
    container_name: build-test
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes:
      - ./src:/src
    command: >
      bash -c "dotnet build src --configuration Release
      && dotnet test src --verbosity normal"
